# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxStateDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya'
  pod 'Moya/RxSwift'
  pod 'SnapKit'
  pod 'ReSwift'
  pod 'ReactorKit'
  pod 'RxViewController'

  target 'RxStateDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
